apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-name-pv
  labels:
    name: app-name-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: /mnt/data
