apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-name-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: app-name-pv
